shiny:
  image:
    repository: registry.gitlab-forge.din.developpement-durable.gouv.fr/dreal-normandie/pole-renovation-energetique/prelshiny_golem
    pullPolicy: Always
    tag: main
  imagePullSecrets:
  - name: regcred
  ingress:
    enabled: true
    hostname: prel.lab.sspcloud.fr
  probe:
    enabled: true
    probeValue:
        livenessProbe:
          timeoutSeconds: 10
        readinessProbe:
          timeoutSeconds: 10
        startupProbe:
          timeoutSeconds: 10  
  s3:
    enabled: false
    existingSecret: myshinyapp-s3
  postgresql:
    enabled: false
    auth:
      username: myusername
      database: defaultdb
      existingSecret: myshinyapp-postgresql
    containerPorts:
      postgresql: 5432
    fullnameOverride: postgresql-db
    primary:
      persistence:
        size: 2Gi
  