shiny:
  image:
    repository: blenzi/gd4h-eau
    pullPolicy: Always
    tag: latest
    containerPort: 8501
  ingress:
    enabled: true
    hostname: gd4h-eau.lab.sspcloud.fr
  s3:
    enabled: true
    existingSecret: myshinyapp-s3
  env:
    - name: GEOAPI_KEY
      valueFrom:
        secretKeyRef:
          name: geoapi-key
